/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AnimalRefugio { 
    adoptado?: boolean;
    colorCaracteristicas: string;
    deleted?: boolean;
    edad: number;
    especie: string;
    fechaNacimiento: Date;
    id?: number;
    idImagenAnimalCld?: string;
    lugarEstancia: string;
    nombre: string;
    nombreImagenAnimalCld?: string;
    observacionesProcedencia: string;
    peso: number;
    procedencia: string;
    raza: string;
    sexo: string;
    urlImagenAnimalCld?: string;
}