/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FichaClinicaDTO } from './fichaClinicaDTO';

export interface AnimalDTO { 
    adoptado?: number;
    colorCaracteristicas?: string;
    edad?: number;
    especie?: string;
    fechaNacimiento?: Date;
    fichasClinicas?: Array<FichaClinicaDTO>;
    foto?: string;
    id?: number;
    lugarEstancia?: string;
    nombre?: string;
    observacionesProcedencia?: string;
    peso?: number;
    procedencia?: string;
    raza?: string;
    sexo?: string;
    tamanyo?: string;
}