/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnimalRefugio } from './animalRefugio';
import { AnimalRefugioResponse } from './animalRefugioResponse';
import { Vacuna } from './vacuna';

export interface CarnetVacunacion { 
    animal?: AnimalRefugioResponse;
    fechaAplicacion?: Date;
    fechaProximaAplicacion?: Date;
    id?: number;
    vacuna?: Vacuna;
}