/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FichaClinicaRequestDTO { 
    alimentacion?: number;
    animalId?: number;
    conjuntiva?: string;
    costo?: number;
    diagnosticoDiferencial?: string;
    esterilizacion?: string;
    examenes_solicitados?: string;
    fechaIngreso?: Date;
    frecuenciaCardiaca?: number;
    frecuenciaRespiratoria?: number;
    hallazgos?: string;
    id?: number;
    motivoConsulta?: string;
    mucosas?: string;
    personaId?: number;
    pronostico?: string;
    temperatura?: number;
    tipoPaciente?: string;
    trc?: string;
}