/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MedicamentoDto } from './medicamentoDto';
import { TratamientoDtoExtends } from './tratamientoDtoExtends';

export interface MedicacionDtoExtends { 
    descripcionMd: string;
    dosis: string;
    duracion: string;
    fechaCaducidad?: string;
    frecuencia: string;
    id?: number;
    medicamento?: MedicamentoDto;
    tratamiento: TratamientoDtoExtends;
}