export * from './adopciones.service';
import { AdopcionesService } from './adopciones.service';
export * from './adoptantes.service';
import { AdoptantesService } from './adoptantes.service';
export * from './animalesRefugio.service';
import { AnimalesRefugioService } from './animalesRefugio.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './carnetsDeVacunacin.service';
import { CarnetsDeVacunacinService } from './carnetsDeVacunacin.service';
export * from './citas.service';
import { CitasService } from './citas.service';
export * from './clientes.service';
import { ClientesService } from './clientes.service';
export * from './donaciones.service';
import { DonacionesService } from './donaciones.service';
export * from './fichasClnicas.service';
import { FichasClnicasService } from './fichasClnicas.service';
export * from './medicaciones.service';
import { MedicacionesService } from './medicaciones.service';
export * from './medicamentos.service';
import { MedicamentosService } from './medicamentos.service';
export * from './personas.service';
import { PersonasService } from './personas.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './seguimientoDeAdoptados.service';
import { SeguimientoDeAdoptadosService } from './seguimientoDeAdoptados.service';
export * from './servicios.service';
import { ServiciosService } from './servicios.service';
export * from './tratamientos.service';
import { TratamientosService } from './tratamientos.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export * from './vacunas.service';
import { VacunasService } from './vacunas.service';
export * from './veterinarios.service';
import { VeterinariosService } from './veterinarios.service';
export * from './voluntarios.service';
import { VoluntariosService } from './voluntarios.service';
export const APIS = [AdopcionesService, AdoptantesService, AnimalesRefugioService, AuthControllerService, CarnetsDeVacunacinService, CitasService, ClientesService, DonacionesService, FichasClnicasService, MedicacionesService, MedicamentosService, PersonasService, RolesService, SeguimientoDeAdoptadosService, ServiciosService, TratamientosService, UsuariosService, VacunasService, VeterinariosService, VoluntariosService];
