/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { SeguimientoAdopcionDto } from '../model/seguimientoAdopcionDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SeguimientoDeAdoptadosService {

    protected basePath = 'https://vinculation.herokuapp.com/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * crearSeguimiento
     * 
     * @param body seguimientoDto
     * @param idAdopcion idAdopcion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public crearSeguimientoUsingPOST(body: SeguimientoAdopcionDto, idAdopcion: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public crearSeguimientoUsingPOST(body: SeguimientoAdopcionDto, idAdopcion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public crearSeguimientoUsingPOST(body: SeguimientoAdopcionDto, idAdopcion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public crearSeguimientoUsingPOST(body: SeguimientoAdopcionDto, idAdopcion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling crearSeguimientoUsingPOST.');
        }

        if (idAdopcion === null || idAdopcion === undefined) {
            throw new Error('Required parameter idAdopcion was null or undefined when calling crearSeguimientoUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/adopciones/seguimientos/${encodeURIComponent(String(idAdopcion))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * editarSeguimiento
     * 
     * @param body seguimientoDto
     * @param idSeguimiento idSeguimiento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public editarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public editarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public editarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editarSeguimientoUsingPUT.');
        }

        if (idSeguimiento === null || idSeguimiento === undefined) {
            throw new Error('Required parameter idSeguimiento was null or undefined when calling editarSeguimientoUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/adopciones/seguimientos/${encodeURIComponent(String(idSeguimiento))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * eliminarSeguimiento
     * 
     * @param idSeguimiento idSeguimiento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eliminarSeguimientoUsingDELETE(idSeguimiento: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public eliminarSeguimientoUsingDELETE(idSeguimiento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public eliminarSeguimientoUsingDELETE(idSeguimiento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public eliminarSeguimientoUsingDELETE(idSeguimiento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSeguimiento === null || idSeguimiento === undefined) {
            throw new Error('Required parameter idSeguimiento was null or undefined when calling eliminarSeguimientoUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/adopciones/seguimientos/${encodeURIComponent(String(idSeguimiento))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * finalizarSeguimiento
     * 
     * @param body seguimientoDto
     * @param idSeguimiento idSeguimiento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public finalizarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public finalizarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public finalizarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public finalizarSeguimientoUsingPUT(body: SeguimientoAdopcionDto, idSeguimiento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling finalizarSeguimientoUsingPUT.');
        }

        if (idSeguimiento === null || idSeguimiento === undefined) {
            throw new Error('Required parameter idSeguimiento was null or undefined when calling finalizarSeguimientoUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/adopciones/seguimientos/finalizar/${encodeURIComponent(String(idSeguimiento))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAdopcionesEnSeguimientoActivo
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAdopcionesEnSeguimientoActivoUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAdopcionesEnSeguimientoActivoUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAdopcionesEnSeguimientoActivoUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAdopcionesEnSeguimientoActivoUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/adopciones/seguimientos/adopciones`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllSeguimientosActivos
     * 
     * @param idAdopcion idAdopcion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAllSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAllSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAllSeguimientosActivosUsingGET(idAdopcion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAdopcion === null || idAdopcion === undefined) {
            throw new Error('Required parameter idAdopcion was null or undefined when calling getAllSeguimientosActivosUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/adopciones/seguimientos/all/enproceso/${encodeURIComponent(String(idAdopcion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllSeguimientosTerminados
     * 
     * @param idAdopcion idAdopcion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllSeguimientosTerminadosUsingGET(idAdopcion: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAllSeguimientosTerminadosUsingGET(idAdopcion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAllSeguimientosTerminadosUsingGET(idAdopcion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAllSeguimientosTerminadosUsingGET(idAdopcion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAdopcion === null || idAdopcion === undefined) {
            throw new Error('Required parameter idAdopcion was null or undefined when calling getAllSeguimientosTerminadosUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/adopciones/seguimientos/all/finalizado/${encodeURIComponent(String(idAdopcion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getNumSeguimientosActivos
     * 
     * @param idAdopcion idAdopcion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNumSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getNumSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getNumSeguimientosActivosUsingGET(idAdopcion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getNumSeguimientosActivosUsingGET(idAdopcion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAdopcion === null || idAdopcion === undefined) {
            throw new Error('Required parameter idAdopcion was null or undefined when calling getNumSeguimientosActivosUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/adopciones/seguimientos/count/${encodeURIComponent(String(idAdopcion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
