export enum ROLE {
	ROLE_ADMIN = "ROLE_ADMIN",
	ROLE_DEFAULT_USER = "ROLE_DEFAULT_USER",
	ROLE_VETERINARIO = "ROLE_VETERINARIO",
}
export const ROLES_POR_MODULOS = {
	MODULO_ANIMALES: [ ROLE.ROLE_ADMIN, ROLE.ROLE_VETERINARIO ],
	MODULO_ADOPCIONES: [ ROLE.ROLE_ADMIN, ROLE.ROLE_VETERINARIO, ROLE.ROLE_DEFAULT_USER ],
	MODULO_PERSONAS: [ ROLE.ROLE_ADMIN ],
	MODULO_USUARIOS: [ ROLE.ROLE_ADMIN ]
};